kind: pipeline
name: development

steps:
  - name: Check coding style
    pull: never
    image: drone/base:golangci-lint-1.47.2
    depends_on: [ clone ]
    commands:
      - golangci-lint run ./...

  - name: Unit test and build
    pull: never
    image: drone/base:gotest
    depends_on: [ clone ]
    commands:
      - gotestsum ./... -v -short -cover
      - make

